### ISSUE TITLE
npm vs yarn

### ISSUE THREAD

**Issue by nonoll** [rk-a4f/a4f-react-boilerplate#20]
- 차이가 어떻게 되는지, 어떤걸 계속 쓸지?

**Comment by dopeboy0608** [comment]
보편적으로 npm 을 많이 사용하는것 같음..
테크인, 위멮 때부터 npm만 사용했었고, 
컬리에 입사후 바로 맡은 프로젝트도 yarn 기반으로 진행하다가 보일러플레이트 교체진행하며 npm 으로 변경..

**Comment by dopeboy0608** [comment]
다른 이슈 진행하며 npm 으로 교체
- yarn.lock 제거
- package.json 스크립트 수정
